package com.wordmind.app.ui

internal enum class PhonemeSection(val label: String, val description: String) {
    ShortVowel("短元音", "发音短促，口形保持相对稳定"),
    LongVowel("长元音", "符号中的 ː 表示声音需要适当延长"),
    Diphthong("双元音", "口形从一个元音平滑滑向另一个元音"),
    Consonant("辅音", "24 个常见英语辅音，包含清浊音、鼻音和近音"),
}

internal data class Phoneme(
    val symbol: String,
    val section: PhonemeSection,
    val soundType: String,
    val tip: String,
    val spellings: List<String>,
    val exampleWord: String,
    val examplePhonetic: String,
    val exampleMeaning: String,
    val moreExamples: List<String>,
)

private fun phoneme(
    symbol: String,
    section: PhonemeSection,
    soundType: String,
    tip: String,
    spellings: String,
    exampleWord: String,
    examplePhonetic: String,
    exampleMeaning: String,
    moreExamples: String,
) = Phoneme(
    symbol = symbol,
    section = section,
    soundType = soundType,
    tip = tip,
    spellings = spellings.split(" "),
    exampleWord = exampleWord,
    examplePhonetic = examplePhonetic,
    exampleMeaning = exampleMeaning,
    moreExamples = moreExamples.split(" "),
)

internal val EnglishPhonemes = listOf(
    phoneme(
        "ɪ",
        PhonemeSection.ShortVowel,
        "短元音",
        "短促的“衣”音。嘴角微微向两侧展开，舌位较高，但肌肉保持放松。",
        "i y",
        "ship",
        "/ʃɪp/",
        "船",
        "sit milk busy",
    ),
    phoneme(
        "ʊ",
        PhonemeSection.ShortVowel,
        "短元音",
        "短促的“乌”音。嘴唇略微收圆，舌后部抬起，不要拖长。",
        "oo u ou",
        "book",
        "/bʊk/",
        "书",
        "good put could",
    ),
    phoneme(
        "e",
        PhonemeSection.ShortVowel,
        "短元音",
        "类似短促的“哎”。嘴唇自然展开，舌尖接近下齿，开口不大。",
        "e ea",
        "bed",
        "/bed/",
        "床",
        "pen head many",
    ),
    phoneme(
        "ə",
        PhonemeSection.ShortVowel,
        "弱元音（schwa）",
        "最放松的弱读音，类似轻轻的“呃”。常出现在非重读音节中。",
        "a e o u er",
        "about",
        "/əˈbaʊt/",
        "关于",
        "teacher support problem",
    ),
    phoneme(
        "æ",
        PhonemeSection.ShortVowel,
        "短元音",
        "介于“啊”和“哎”之间。嘴巴张大，舌位较低，声音短而有力。",
        "a",
        "cat",
        "/kæt/",
        "猫",
        "map hand black",
    ),
    phoneme(
        "ʌ",
        PhonemeSection.ShortVowel,
        "短元音",
        "短促的中央“啊”音。嘴巴自然张开，舌头放松，不要读成拼音 a。",
        "u o ou",
        "cup",
        "/kʌp/",
        "杯子",
        "sun love young",
    ),
    phoneme(
        "ɒ",
        PhonemeSection.ShortVowel,
        "短元音（英音）",
        "短促的“奥”音。嘴唇略圆、开口较大；英式发音中很常见。",
        "o a",
        "hot",
        "/hɒt/",
        "热的",
        "dog clock want",
    ),
    phoneme(
        "iː",
        PhonemeSection.LongVowel,
        "长元音",
        "拉长的“衣”音。嘴角向两侧展开，舌位高，保持声音稳定。",
        "ee ea e ie",
        "sheep",
        "/ʃiːp/",
        "绵羊",
        "see eat piece",
    ),
    phoneme(
        "uː",
        PhonemeSection.LongVowel,
        "长元音",
        "拉长的“乌”音。双唇收圆并向前突出，舌后部抬起。",
        "oo u ue ew",
        "blue",
        "/bluː/",
        "蓝色的",
        "moon food new",
    ),
    phoneme(
        "ɑː",
        PhonemeSection.LongVowel,
        "长元音",
        "拉长的“啊”音。嘴巴张大，舌位低而靠后，声音要饱满。",
        "ar a",
        "car",
        "/kɑː/",
        "汽车",
        "farm father class",
    ),
    phoneme(
        "ɔː",
        PhonemeSection.LongVowel,
        "长元音",
        "拉长的“奥”音。嘴唇收圆，舌后部抬起，声音持续稳定。",
        "or aw au oor",
        "door",
        "/dɔː/",
        "门",
        "horse saw talk",
    ),
    phoneme(
        "ɜː",
        PhonemeSection.LongVowel,
        "长元音",
        "拉长的中央元音。嘴唇自然，舌身居中；英音中不要卷舌。",
        "ir ur er ear",
        "bird",
        "/bɜːd/",
        "鸟",
        "girl turn learn",
    ),
    phoneme(
        "eɪ",
        PhonemeSection.Diphthong,
        "双元音",
        "从 /e/ 平滑滑向 /ɪ/，类似“诶”的变化音，前半部分更清楚。",
        "a ai ay ei",
        "face",
        "/feɪs/",
        "脸",
        "day rain eight",
    ),
    phoneme(
        "aɪ",
        PhonemeSection.Diphthong,
        "双元音",
        "从开口较大的 /a/ 滑向 /ɪ/，类似“爱”，口形由大变小。",
        "i y igh ie",
        "time",
        "/taɪm/",
        "时间",
        "my night pie",
    ),
    phoneme(
        "ɔɪ",
        PhonemeSection.Diphthong,
        "双元音",
        "从圆唇的 /ɔ/ 滑向 /ɪ/，类似“奥依”，注意连贯完成。",
        "oy oi",
        "boy",
        "/bɔɪ/",
        "男孩",
        "toy coin voice",
    ),
    phoneme(
        "əʊ",
        PhonemeSection.Diphthong,
        "双元音（英音）",
        "从放松的中央元音滑向 /ʊ/，嘴唇逐渐收圆，类似“欧”。",
        "o oa ow oe",
        "goat",
        "/ɡəʊt/",
        "山羊",
        "go boat snow",
    ),
    phoneme(
        "aʊ",
        PhonemeSection.Diphthong,
        "双元音",
        "从张口的 /a/ 滑向圆唇的 /ʊ/，类似“奥”，口形变化要明显。",
        "ou ow",
        "house",
        "/haʊs/",
        "房子",
        "now mouth cloud",
    ),
    phoneme(
        "ɪə",
        PhonemeSection.Diphthong,
        "双元音（英音）",
        "从 /ɪ/ 滑向放松的 /ə/。开头较清楚，结尾自然弱化。",
        "ear eer ere",
        "near",
        "/nɪə/",
        "近的",
        "here dear beer",
    ),
    phoneme(
        "eə",
        PhonemeSection.Diphthong,
        "双元音（英音）",
        "从 /e/ 滑向 /ə/。嘴巴由略展开变为自然放松。",
        "air are ear",
        "hair",
        "/heə/",
        "头发",
        "care chair bear",
    ),
    phoneme(
        "ʊə",
        PhonemeSection.Diphthong,
        "双元音（英音）",
        "从圆唇的 /ʊ/ 滑向 /ə/。现代口音中常与其他元音合并。",
        "our ure oor",
        "tour",
        "/tʊə/",
        "旅行",
        "poor cure pure",
    ),
    phoneme(
        "p",
        PhonemeSection.Consonant,
        "清辅音 · 爆破音",
        "双唇闭合后突然放开送气，声带不振动。把手放在嘴前可感到气流。",
        "p pp",
        "pen",
        "/pen/",
        "钢笔",
        "map happy stop",
    ),
    phoneme(
        "b",
        PhonemeSection.Consonant,
        "浊辅音 · 爆破音",
        "双唇闭合后放开，动作与 /p/ 相似，但声带振动、送气较弱。",
        "b bb",
        "bag",
        "/bæɡ/",
        "包",
        "book rabbit cab",
    ),
    phoneme(
        "t",
        PhonemeSection.Consonant,
        "清辅音 · 爆破音",
        "舌尖抵住上齿龈后迅速放开送气，声带不振动。",
        "t tt",
        "tea",
        "/tiː/",
        "茶",
        "top letter cat",
    ),
    phoneme(
        "d",
        PhonemeSection.Consonant,
        "浊辅音 · 爆破音",
        "舌尖抵住上齿龈后放开，声带振动，是 /t/ 的浊音搭档。",
        "d dd",
        "dog",
        "/dɒɡ/",
        "狗",
        "day middle red",
    ),
    phoneme(
        "tʃ",
        PhonemeSection.Consonant,
        "清辅音 · 破擦音",
        "舌前部先阻住气流再摩擦放出，类似“吃”但更短，声带不振动。",
        "ch tch t",
        "chair",
        "/tʃeə/",
        "椅子",
        "child watch picture",
    ),
    phoneme(
        "dʒ",
        PhonemeSection.Consonant,
        "浊辅音 · 破擦音",
        "动作与 /tʃ/ 相似，但声带振动，类似短促的“知”。",
        "j g dge",
        "jump",
        "/dʒʌmp/",
        "跳",
        "job giant bridge",
    ),
    phoneme(
        "k",
        PhonemeSection.Consonant,
        "清辅音 · 爆破音",
        "舌后部抵住软腭后突然放开送气，声带不振动。",
        "c k ck ch",
        "cat",
        "/kæt/",
        "猫",
        "key back school",
    ),
    phoneme(
        "ɡ",
        PhonemeSection.Consonant,
        "浊辅音 · 爆破音",
        "舌后部抵住软腭后放开，声带振动，是 /k/ 的浊音搭档。",
        "g gg",
        "go",
        "/ɡəʊ/",
        "去",
        "game bigger dog",
    ),
    phoneme(
        "f",
        PhonemeSection.Consonant,
        "清辅音 · 摩擦音",
        "上齿轻触下唇，让气流从缝隙摩擦而出，声带不振动。",
        "f ff ph gh",
        "fish",
        "/fɪʃ/",
        "鱼",
        "phone coffee laugh",
    ),
    phoneme(
        "v",
        PhonemeSection.Consonant,
        "浊辅音 · 摩擦音",
        "上齿轻触下唇，保持摩擦并让声带振动，不要读成 /w/。",
        "v ve",
        "van",
        "/væn/",
        "货车",
        "very seven love",
    ),
    phoneme(
        "θ",
        PhonemeSection.Consonant,
        "清辅音 · 摩擦音",
        "舌尖轻放在上下齿之间，气流从舌齿间通过，声带不振动。",
        "th",
        "think",
        "/θɪŋk/",
        "思考",
        "three mouth healthy",
    ),
    phoneme(
        "ð",
        PhonemeSection.Consonant,
        "浊辅音 · 摩擦音",
        "舌位与 /θ/ 相同，但声带振动。常出现在 this、that 等高频词中。",
        "th",
        "this",
        "/ðɪs/",
        "这个",
        "that mother breathe",
    ),
    phoneme(
        "s",
        PhonemeSection.Consonant,
        "清辅音 · 摩擦音",
        "舌尖靠近上齿龈，让气流从中间窄缝通过，声带不振动。",
        "s ss c",
        "sun",
        "/sʌn/",
        "太阳",
        "city class rice",
    ),
    phoneme(
        "z",
        PhonemeSection.Consonant,
        "浊辅音 · 摩擦音",
        "舌位与 /s/ 相同，但声带振动，像蜜蜂持续的嗡鸣声。",
        "z zz s",
        "zoo",
        "/zuː/",
        "动物园",
        "zero busy nose",
    ),
    phoneme(
        "ʃ",
        PhonemeSection.Consonant,
        "清辅音 · 摩擦音",
        "舌前部靠近上齿龈后方，双唇略圆，发出安静提示的“嘘”声。",
        "sh ti ci s",
        "shoe",
        "/ʃuː/",
        "鞋",
        "ship nation special",
    ),
    phoneme(
        "ʒ",
        PhonemeSection.Consonant,
        "浊辅音 · 摩擦音",
        "舌位与 /ʃ/ 相似，但声带振动。英语中多出现在词中间。",
        "s si ge",
        "vision",
        "/ˈvɪʒən/",
        "视力；景象",
        "usual measure garage",
    ),
    phoneme(
        "m",
        PhonemeSection.Consonant,
        "浊辅音 · 鼻音",
        "双唇闭合，气流从鼻腔通过，声带振动。",
        "m mm",
        "moon",
        "/muːn/",
        "月亮",
        "map summer team",
    ),
    phoneme(
        "n",
        PhonemeSection.Consonant,
        "浊辅音 · 鼻音",
        "舌尖抵住上齿龈，气流从鼻腔通过，声带振动。",
        "n nn kn",
        "nose",
        "/nəʊz/",
        "鼻子",
        "name dinner know",
    ),
    phoneme(
        "ŋ",
        PhonemeSection.Consonant,
        "浊辅音 · 鼻音",
        "舌后部抵住软腭，气流从鼻腔通过。结尾不要额外加 /ɡ/。",
        "ng n",
        "sing",
        "/sɪŋ/",
        "唱歌",
        "long singer think",
    ),
    phoneme(
        "h",
        PhonemeSection.Consonant,
        "清辅音 · 摩擦音",
        "声门打开，让气流轻轻呼出，像对着玻璃哈气，声带不振动。",
        "h wh",
        "hat",
        "/hæt/",
        "帽子",
        "home behind who",
    ),
    phoneme(
        "l",
        PhonemeSection.Consonant,
        "浊辅音 · 边音",
        "舌尖抵住上齿龈，气流从舌头两侧通过，声带振动。",
        "l ll",
        "leg",
        "/leɡ/",
        "腿",
        "light yellow feel",
    ),
    phoneme(
        "r",
        PhonemeSection.Consonant,
        "浊辅音 · 近音",
        "舌尖抬起但不要触碰上颚，双唇略圆。英音词尾的 r 常不发音。",
        "r rr wr",
        "red",
        "/red/",
        "红色的",
        "run sorry write",
    ),
    phoneme(
        "w",
        PhonemeSection.Consonant,
        "浊辅音 · 近音",
        "双唇先收圆，再迅速滑向后面的元音，声带振动。",
        "w wh u",
        "wet",
        "/wet/",
        "湿的",
        "water quick when",
    ),
    phoneme(
        "j",
        PhonemeSection.Consonant,
        "浊辅音 · 近音",
        "类似汉语“衣”的起始滑音，舌前部抬高后迅速滑向元音。",
        "y u ew",
        "yes",
        "/jes/",
        "是的",
        "you use few",
    ),
)
